# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7e60ffc08e2bf160c3c0f4294bdf743c67aac357baa2123e09bf65a5656291631c2ac3679654e4a55e4a3d73d4f68b6d335de499b7e580de111316b6326a5dea

test:
  secret_key_base: a8bfcd88692736671334663cc29705e7af00c773e9ee1ca3af2bcb80af88be9ac2d92152300958b672923b296cf4796bcd2b82fff804bce49956263d77065aac

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
